### ISSUE TITLE
[1차 화면구현] 메인 페이지

### ISSUE THREAD

**Issue by vgbhn37** [vgbhn37/jejuplus#6]
메인페이지 http://localhost/main

- [x] 날씨 위젯 (더 좋은것 있으면 교체 가능)
- [x] 스케줄 선택
- [x] 상품 리스트

**Comment by SBUX1992** [comment]
2023-10-23
1. header
 - jeju 날씨 toggle 사용해서 위젯 팝업 완료
 - 로고 및 각종 링크 작성

2. main
 - 날짜 선택 구현(사용여부 미정)
 - 인기 추천 등 숙박, 패키지 상품 게시

3. footer
 - 회사 주소 및 입금내역 등 기타정보 기재 완료

**Comment by SBUX1992** [comment]
2023-10-24
1. 메인 페이지 화면구현 완료
 - 차후 개발 방향에 따라 디테일 수정
